version = 0.1
[development]
[development.deploy]
[development.deploy.parameters]
stack_name = "pci-briefcase-development-service"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-ik2h1h0nlnqs"
s3_prefix = "pci-briefcase-development-service"
region = "us-east-1"
capabilities = "CAPABILITY_IAM"
parameter_overrides = "ServiceName=\"briefcase\" Environment=\"development\""
image_repositories = []
